### ISSUE TITLE
Lien erroné dans l'aide

### ISSUE THREAD

**Issue by Badatos** [betagouv/pix#399]
Bonjour,
Le fichier Readme.md (dans le point 3/) contient un lien vers "https://github.com/orgs/sgmap/teams/pix", or ceci renvoi une page 404.

D'ailleurs, il semble qu'une "Airtable API key" soit nécessaire pour tester le logiciel Pix. pouvez-vous m'indiquer comment l'obtenir svp ?

**Comment by jbuget** [comment]
Bonjour Olivier,

Concernant le lien, il semblerait qu'il ne soit accessible que pour les membres de l'organisation.
Nous allons voir pour rendre le lien accessible au grand public ou proposer un autre moyen de contact.

Concernant la clé Airtable, nous réfléchissons à un moyen optimal (à la fois sécurisé mais en même temps ouvert) de pouvoir fournir une base et une clé de test.

Nous vous tiendrons au courant dans l'avancée de l'un et l'autre chantier.

Merci de votre vigilance et de votre intérêt pour PIX.

:-)

**Comment by Badatos** [comment]
Attention : le lien indiqué dans ce ticket existe toujours, et renvoi toujours vers une page 404.
